services:
  app:
    image: &app_image ghcr.io/cognologos/cognologos-materials-service

    restart: unless-stopped

    env_file: &app_env_file
      - .env

    environment: &app_environment
      MODE: app

    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_started
      redis:
        condition: service_healthy

    healthcheck: &healthcheck
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 1s

    ports:
      - 8000:8000

  migrations:
    image: *app_image

    env_file: *app_env_file

    environment:
      <<: *app_environment
      MODE: migrations

    healthcheck:
      disable: true

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:7.0

    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - 127.0.0.1:27017:27017

    volumes:
      - mongodb-data:/data/db

    healthcheck: &service_healthcheck
      test: ["CMD", "mongo", "mongodb://user:password@localhost:27017/user", "--eval", "db.runCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 2s

  redis:
    image: redis:7-alpine

    restart: unless-stopped

    healthcheck:
      <<: *service_healthcheck
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1s
      start_interval: 1s
