services:
  db:
    image: mongo:7.0

    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - 127.0.0.1:27017:27017

  redis:
    image: redis:7-alpine

    ports:
      - 127.0.0.1:6379:6379

